/** Shared Meta UTILITY name for Instant templates — one APPROVED body {{1}} per Page. */
export const INSTANT_PLAIN_UTILITY_NAME = 'castme_plain_utility_v1';

/** Quick-fill chips under BODY {{n}} fields (Page Instant–style). */
export const TEMPLATE_QUICK_CHIPS: readonly { label: string; value: string }[] = [
  { label: "%{name} · client's name", value: '{{first_name}}' },
  { label: 'LOVE', value: 'LOVE' },
  { label: 'MEGA BONUS', value: 'MEGA BONUS' },
  { label: '100% SIGNUP', value: '100% SIGNUP' },
  { label: 'FREEPLAY', value: 'FREEPLAY' },
  { label: 'GAMES ARE HITTING', value: 'GAMES ARE HITTING' },
];

/** Full CastMe starter library — Template-1…33 bodies match pageinstant.com/library exactly. */
export type StarterUtilityTemplate = {
  id: string;
  name: string;
  title: string;
  badge: string;
  description: string;
  body: string;
  parameters: string[];
  labels: string[];
  examples: string[];
  /** When true, send via castme_plain_utility_v1. */
  instant?: boolean;
};

export const STARTER_UTILITY_TEMPLATES: readonly StarterUtilityTemplate[] = [
  // —— Page Instant Template-N (exact bodies from pageinstant.com/library) ——
  {
    id: 'template_33',
    name: 'castme_pi_t33_v1',
    title: 'Template-33',
    badge: 'EN',
    description: 'Page Instant Template-33',
    body: "{{1}} your order is confirmed \n\n🔴 {{2}}\n\n🔵 {{3}}\n\n⚫ {{4}}\n\n⚪ {{5}}\n\nreply me 📩 if you want",
    parameters: ["field_1","field_2","field_3","field_4","field_5"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}"],
    examples: ["John","Detail 1","Detail 2","Detail 3","Detail 4"],
  },
  {
    id: 'template_32',
    name: 'castme_pi_t32_v1',
    title: 'Template-32',
    badge: 'EN',
    description: 'Page Instant Template-32',
    body: "🚀 {{1}}\n\nconfirmed ✅",
    parameters: ["field_1"],
    labels: ["BODY {{1}}"],
    examples: ["John"],
  },
  {
    id: 'template_31',
    name: 'castme_pi_t31_v1',
    title: 'Template-31',
    badge: 'EN',
    description: 'Page Instant Template-31',
    body: "{{1}} your order\n\n📌 {{2}} 📌\n\n✅ {{3}} ✅\n\n👀 {{4}} 👀\n\n💥 {{5}} 💥\n\nreply me if you have any questions",
    parameters: ["field_1","field_2","field_3","field_4","field_5"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}"],
    examples: ["John","Detail 1","Detail 2","Detail 3","Detail 4"],
  },
  {
    id: 'template_30',
    name: 'castme_pi_t30_v1',
    title: 'Template-30',
    badge: 'EN',
    description: 'Page Instant Template-30',
    body: "😎 Hi {{1}}\n\n💎 {{2}} • 🏆 {{3}}\n\n💵 {{5}} • 💳 {{6}}\n\n✔ {{4}} Now\n\nReview your account settings.",
    parameters: ["field_1","field_2","field_3","field_4","field_5","field_6"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}","BODY {{6}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3","Detail 4","Detail 5"],
  },
  {
    id: 'template_29',
    name: 'castme_pi_t29_v1',
    title: 'Template-29',
    badge: 'EN',
    description: 'Page Instant Template-29',
    body: "😎 Hi {{1}},\n\n💎 {{2}}\n🏆 {{3}}\n💎 {{4}}\n\n💵 {{5}}\n💳 {{6}}\n\nReply YES to review your billing details.",
    parameters: ["field_1","field_2","field_3","field_4","field_5","field_6"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}","BODY {{6}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3","Detail 4","Detail 5"],
  },
  {
    id: 'template_28',
    name: 'castme_pi_t28_v1',
    title: 'Template-28',
    badge: 'EN',
    description: 'Page Instant Template-28',
    body: "👑 Hello {{1}},\n\nHere's your latest membership information.\n\n🏆 {{2}}\n📅 {{3}}\n🟢 {{4}}\n\nReply YES to {{5}}.",
    parameters: ["field_1","field_2","field_3","field_4","field_5"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3","Detail 4"],
  },
  {
    id: 'template_27',
    name: 'castme_pi_t27_v1',
    title: 'Template-27',
    badge: 'EN',
    description: 'Page Instant Template-27',
    body: "Hi {{1}}, ❤❤\n\n💎 there's an update on your account: \n\n🏆 {{2}}\n🔔 {{3}}\n💸 {{4}}\n💵 {{5}}\n✅ {{6}}\n\nReply yes if you Want {{7}}📩",
    parameters: ["field_1","field_2","field_3","field_4","field_5","field_6","field_7"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}","BODY {{6}}","BODY {{7}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3","Detail 4","Detail 5","Detail 6"],
  },
  {
    id: 'template_26',
    name: 'castme_pi_t26_v1',
    title: 'Template-26',
    badge: 'EN',
    description: 'Page Instant Template-26',
    body: "Hey {{1}} 🔥, \n\n{{2}} just got ACTIVATED. 🎉\n\nNow Get : \n\n🎯 {{3}}\n🎯 {{4}}\n🎯 {{5}}\n\nReply if you need any assistance.",
    parameters: ["field_1","field_2","field_3","field_4","field_5"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3","Detail 4"],
  },
  {
    id: 'template_25',
    name: 'castme_pi_t25_v1',
    title: 'Template-25',
    badge: 'EN',
    description: 'Page Instant Template-25',
    body: "Hello {{1}} 🎁, {{2}} has been ACTIVATED for you! ❤",
    parameters: ["field_1","field_2"],
    labels: ["BODY {{1}}","BODY {{2}}"],
    examples: ["Ahmed","Detail 1"],
  },
  {
    id: 'template_24',
    name: 'castme_pi_t24_v1',
    title: 'Template-24',
    badge: 'EN',
    description: 'Page Instant Template-24',
    body: "Hello {{1}} 👋\n\nYour player status has been updated.\n\n✅ {{2}}\n🎁  {{3}}\n⚡  {{4}}\n\nReply if you need any assistance.",
    parameters: ["field_1","field_2","field_3","field_4"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3"],
  },
  {
    id: 'template_23',
    name: 'castme_pi_t23_v1',
    title: 'Template-23',
    badge: 'EN',
    description: 'Page Instant Template-23',
    body: "Hello {{1}} ❤❤,\n\n{{2}} is now ACTIVE. 💸",
    parameters: ["field_1","field_2"],
    labels: ["BODY {{1}}","BODY {{2}}"],
    examples: ["Ahmed","Detail 1"],
  },
  {
    id: 'template_22',
    name: 'castme_pi_t22_v1',
    title: 'Template-22',
    badge: 'EN',
    description: 'Page Instant Template-22',
    body: "Hello {{1}} 👀,\n\n{{2}} is now ACTIVE. ✅\n\n💸 {{3}}\n🏆 {{4}}\n\nReply if you have any questions. ❤️",
    parameters: ["field_1","field_2","field_3","field_4"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3"],
  },
  {
    id: 'template_21',
    name: 'castme_pi_t21_v1',
    title: 'Template-21',
    badge: 'EN',
    description: 'Page Instant Template-21',
    body: "Hi {{1}},🔥🔥\n\nYour {{2}} is now confirmed. ✅\n\n✅ {{3}}\n✅ {{4}}\n✅ {{5}}\n\nReply to this message if you have any questions.",
    parameters: ["field_1","field_2","field_3","field_4","field_5"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3","Detail 4"],
  },
  {
    id: 'template_20',
    name: 'castme_pi_t20_v1',
    title: 'Template-20',
    badge: 'EN',
    description: 'Page Instant Template-20',
    body: "🔔 {{1}}\n\n✅ {{2}}\n\n✅ {{3}}\n\n✅ {{4}}\n\nReply if you need assistance.",
    parameters: ["field_1","field_2","field_3","field_4"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}"],
    examples: ["Account Update","Detail 1","Detail 2","Detail 3"],
  },
  {
    id: 'template_19',
    name: 'castme_pi_t19_v1',
    title: 'Template-19',
    badge: 'EN',
    description: 'Page Instant Template-19',
    body: "{{1}} is confirmed 🔥🔥\n\n🎯 {{2}}\n🎯 {{3}}\n🎯 {{4}}\n🎯 {{5}}\n\n📩 Say yes if you want {{6}}",
    parameters: ["field_1","field_2","field_3","field_4","field_5","field_6"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}","BODY {{6}}"],
    examples: ["Account Update","Detail 1","Detail 2","Detail 3","Detail 4","Detail 5"],
  },
  {
    id: 'template_18',
    name: 'castme_pi_t18_v1',
    title: 'Template-18',
    badge: 'EN',
    description: 'Page Instant Template-18',
    body: "🔥 {{1}} \n\n🎁 {{2}} is confirmed 🎁\n\n✅ {{3}}\n✅ {{4}}\n\n📩 Say yes if you want {{5}}",
    parameters: ["field_1","field_2","field_3","field_4","field_5"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}"],
    examples: ["Account Update","Detail 1","Detail 2","Detail 3","Detail 4"],
  },
  {
    id: 'template_17',
    name: 'castme_pi_t17_v1',
    title: 'Template-17',
    badge: 'EN',
    description: 'Page Instant Template-17',
    body: "🔔 Hi {{1}}, your account update has been completed successfully. \n⌛ {{2}}",
    parameters: ["field_1","field_2"],
    labels: ["BODY {{1}}","BODY {{2}}"],
    examples: ["Ahmed","Detail 1"],
  },
  {
    id: 'template_16',
    name: 'castme_pi_t16_v1',
    title: 'Template-16',
    badge: 'EN',
    description: 'Page Instant Template-16',
    body: "🔥 Hi  your {{1}},  is  Now confirmed✅",
    parameters: ["field_1"],
    labels: ["BODY {{1}}"],
    examples: ["Ahmed"],
  },
  {
    id: 'template_15',
    name: 'castme_pi_t15_v1',
    title: 'Template-15',
    badge: 'EN',
    description: 'Page Instant Template-15',
    body: "Hello {{1}}, ❤❤\n\n✅ {{2}} has been updated✅\n\n{{3}} ⏳\n\nReply if you have any questions. ❤",
    parameters: ["field_1","field_2","field_3"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}"],
    examples: ["Ahmed","Detail 1","Detail 2"],
  },
  {
    id: 'template_14',
    name: 'castme_pi_t14_v1',
    title: 'Template-14',
    badge: 'EN',
    description: 'Page Instant Template-14',
    body: "Hi {{1}} 👏\n\nYour {{2}} is activate right now... \n\n✅{{3}} \n\n✅{{4}}\n\n✅{{5}}\n\n✅{{6}}\n\nReply if you have any questions.",
    parameters: ["field_1","field_2","field_3","field_4","field_5","field_6"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}","BODY {{6}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3","Detail 4","Detail 5"],
  },
  {
    id: 'template_13',
    name: 'castme_pi_t13_v1',
    title: 'Template-13',
    badge: 'EN',
    description: 'Page Instant Template-13',
    body: "Hi {{1}} 👀,\n\nYour  {{2}} is ready.✅\n{{3}}\n\nReply if you have any questions.",
    parameters: ["field_1","field_2","field_3"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}"],
    examples: ["Ahmed","Detail 1","Detail 2"],
  },
  {
    id: 'template_12',
    name: 'castme_pi_t12_v1',
    title: 'Template-12',
    badge: 'EN',
    description: 'Page Instant Template-12',
    body: "📂 {{1}}\n\n🟢 {{2}}\n🟢 {{3}}\n🟢 {{4}}\n\nReply if you need assistance.",
    parameters: ["field_1","field_2","field_3","field_4"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}"],
    examples: ["Account Update","Detail 1","Detail 2","Detail 3"],
  },
  {
    id: 'template_11',
    name: 'castme_pi_t11_v1',
    title: 'Template-11',
    badge: 'EN',
    description: 'Page Instant Template-11',
    body: "Hi {{1}} 👏\n\nYour {{2}} is activate right now... \n\n✅{{3}} \n\n✅{{4}}\n\n✅{{5}}\n\n✅{{6}}\n\nReply if you have any questions.",
    parameters: ["field_1","field_2","field_3","field_4","field_5","field_6"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}","BODY {{6}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3","Detail 4","Detail 5"],
  },
  {
    id: 'template_10',
    name: 'castme_pi_t10_v1',
    title: 'Template-10',
    badge: 'EN',
    description: 'Page Instant Template-10',
    body: "Hi! {{1}} is now confirmed.\n\n✅ - {{2}}\n✅ - {{3}}\n✅ - {{4}}\n\nTime : {{5}} ⌛",
    parameters: ["field_1","field_2","field_3","field_4","field_5"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3","Detail 4"],
  },
  {
    id: 'template_9',
    name: 'castme_pi_t09_v1',
    title: 'Template-9',
    badge: 'EN',
    description: 'Page Instant Template-9',
    body: "Hi {{1}},👀\n \n💸Your {{2}} is complete.✅✅\n \n{{3}}🎉\n\nReply if you have any questions.",
    parameters: ["field_1","field_2","field_3"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}"],
    examples: ["Ahmed","Detail 1","Detail 2"],
  },
  {
    id: 'template_8',
    name: 'castme_pi_t08_v1',
    title: 'Template-8',
    badge: 'EN',
    description: 'Page Instant Template-8',
    body: "🔥 {{1}} \n\n💸 {{2}} is confirmed 💸\n\n📩 Say yes if you want {{3}}",
    parameters: ["field_1","field_2","field_3"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}"],
    examples: ["Account Update","Detail 1","Detail 2"],
  },
  {
    id: 'template_7',
    name: 'castme_pi_t07_v1',
    title: 'Template-7',
    badge: 'EN',
    description: 'Page Instant Template-7',
    body: "Hi {{1}},  #{{2}} is ready🔥🔥\n\n📩 Say yes if you want {{3}}",
    parameters: ["field_1","field_2","field_3"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}"],
    examples: ["Ahmed","Detail 1","Detail 2"],
  },
  {
    id: 'template_6',
    name: 'castme_pi_t06_v1',
    title: 'Template-6',
    badge: 'EN',
    description: 'Page Instant Template-6',
    body: "Hi {{1}} 👏\n\nYour {{2}} is activate right now... \n\n✅{{3}} \n\n✅{{4}}\n\n✅{{5}}\n\n✅{{6}}\n\nReply if you have any questions.",
    parameters: ["field_1","field_2","field_3","field_4","field_5","field_6"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}","BODY {{5}}","BODY {{6}}"],
    examples: ["Ahmed","Detail 1","Detail 2","Detail 3","Detail 4","Detail 5"],
  },
  {
    id: 'template_5',
    name: 'castme_pi_t05_v1',
    title: 'Template-5',
    badge: 'EN',
    description: 'Page Instant Template-5',
    body: "🔔 {{1}}\n\nYour account information has been updated.\n\n📄 {{2}}\n📅 {{3}}\n🔖 {{4}}\n\nReply if you need assistance.",
    parameters: ["field_1","field_2","field_3","field_4"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}"],
    examples: ["Account Update","Detail 1","Detail 2","Detail 3"],
  },
  {
    id: 'template_4',
    name: 'castme_pi_t04_v1',
    title: 'Template-4',
    badge: 'EN',
    description: 'Page Instant Template-4',
    body: "{{1}} ❤\n\nYour information has been refreshed.\n\n✅ {{2}}\n📂 {{3}}\n🔖 {{4}}\n\nReply if you need assistance.",
    parameters: ["field_1","field_2","field_3","field_4"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}"],
    examples: ["Account Update","Detail 1","Detail 2","Detail 3"],
  },
  {
    id: 'template_3',
    name: 'castme_pi_t03_v1',
    title: 'Template-3',
    badge: 'EN',
    description: 'Page Instant Template-3',
    body: "{{1}}\n\nYour Status has been Updated\n\n✔️ {{2}}\n📄 {{3}}\n🕒 {{4}}\n\nReply if you need assistance.",
    parameters: ["field_1","field_2","field_3","field_4"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}"],
    examples: ["Account Update","Detail 1","Detail 2","Detail 3"],
  },
  {
    id: 'template_2',
    name: 'castme_pi_t02_v1',
    title: 'Template-2',
    badge: 'EN',
    description: 'Page Instant Template-2',
    body: "🔥 {{1}} \n\n💸 {{2}} is confirmed 💸\n\n📩 Say yes if you want {{3}}",
    parameters: ["field_1","field_2","field_3"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}"],
    examples: ["Account Update","Detail 1","Detail 2"],
  },
  {
    id: 'template_1',
    name: 'castme_pi_t01_v1',
    title: 'Template-1',
    badge: 'EN',
    description: 'Page Instant Template-1',
    body: "🔔 {{1}}\n\n✅ {{2}}\n\n✅ {{3}}\n\n✅ {{4}}\n\nReply if you need assistance.",
    parameters: ["field_1","field_2","field_3","field_4"],
    labels: ["BODY {{1}}","BODY {{2}}","BODY {{3}}","BODY {{4}}"],
    examples: ["Account Update","Detail 1","Detail 2","Detail 3"],
  },

  // —— Instant: shared castme_plain_utility_v1 ——
  {
    id: 'instant_bonus_active',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Bonus Active',
    badge: 'Instant',
    description: 'Shared plain UTILITY — no new Meta template once plain is ready',
    body: "Hello {{1}} ❤️❤️, {{2}} is now ACTIVE. ☘️",
    parameters: ["customer_name","what_is_active"],
    labels: ["Customer name","What is active"],
    examples: ["Friend","30% Bonus"],
    instant: true,
  },
  {
    id: 'instant_vip_unlock',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · VIP Unlocked',
    badge: 'Instant',
    description: 'Instant plain UTILITY',
    body: "Hey {{1}} 🔥, your {{2}} is unlocked. Reply YES for help. ✅",
    parameters: ["customer_name","vip_perk"],
    labels: ["Customer name","VIP / perk"],
    examples: ["Friend","VIP access"],
    instant: true,
  },
  {
    id: 'instant_wallet_update',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Wallet Updated',
    badge: 'Instant',
    description: 'Instant plain UTILITY',
    body: "Hi {{1}} 👀, your {{2}} was updated. {{3}} 💸",
    parameters: ["customer_name","what_updated","detail"],
    labels: ["Customer name","What updated","Detail"],
    examples: ["Friend","wallet","Balance is ready to use."],
    instant: true,
  },
  {
    id: 'instant_offer_cta',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Offer CTA',
    badge: 'Instant',
    description: 'Instant plain UTILITY',
    body: "Hello {{1}} 🎁, {{2}} is ready for you. Reply YES if you want {{3}}.",
    parameters: ["customer_name","offer_name","cta"],
    labels: ["Customer name","Offer","CTA"],
    examples: ["Friend","today's bonus","free spins"],
    instant: true,
  },
  {
    id: 'instant_status_ok',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Status Confirmed',
    badge: 'Instant',
    description: 'Instant plain UTILITY',
    body: "Hi {{1}} ✅, your {{2}} is confirmed. Reply if you need help.",
    parameters: ["customer_name","what_confirmed"],
    labels: ["Customer name","What confirmed"],
    examples: ["Friend","account status"],
    instant: true,
  },
  {
    id: 'instant_reward_ready',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Reward Ready',
    badge: 'Instant',
    description: 'Instant plain UTILITY',
    body: "{{1}}, your {{2}} is ready 🎉. {{3}}",
    parameters: ["customer_name","reward","extra"],
    labels: ["Customer name","Reward","Extra note"],
    examples: ["Friend","daily reward","Claim it in the app."],
    instant: true,
  },
  {
    id: 'instant_support_done',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Issue Resolved',
    badge: 'Instant',
    description: 'Instant plain UTILITY',
    body: "Hi {{1}}, your {{2}} is resolved ✅. {{3}}",
    parameters: ["customer_name","issue","note"],
    labels: ["Customer name","Issue","Note"],
    examples: ["Friend","request","Thanks for your patience."],
    instant: true,
  },
  {
    id: 'instant_reminder',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Reminder',
    badge: 'Instant',
    description: 'Instant plain UTILITY',
    body: "Hello {{1}} 🔔, reminder: {{2}}. Reply if you need assistance.",
    parameters: ["customer_name","reminder"],
    labels: ["Customer name","Reminder"],
    examples: ["Friend","your bonus expires soon"],
    instant: true,
  },
] as const;

export const STARTER_UTILITY_TEMPLATE_COUNT = STARTER_UTILITY_TEMPLATES.length;
