/** Shared Meta UTILITY name for Instant templates — one APPROVED body {{1}} per Page. */
export const INSTANT_PLAIN_UTILITY_NAME = 'castme_plain_utility_v1';

/** Quick-fill chips under BODY {{n}} fields (Page Instant–style). */
export const TEMPLATE_QUICK_CHIPS: readonly { label: string; value: string }[] = [
  { label: "%{name} · client's name", value: '{{first_name}}' },
  { label: 'LOVE', value: 'LOVE' },
  { label: 'MEGA BONUS', value: 'MEGA BONUS' },
  { label: '100% SIGNUP', value: '100% SIGNUP' },
  { label: 'FREEPLAY', value: 'FREEPLAY' },
  { label: 'GAMES ARE HITTING', value: 'GAMES ARE HITTING' },
];

/** Full CastMe starter library (Page Instant–aligned Template-N display + Instant presets). */
export type StarterUtilityTemplate = {
  id: string;
  name: string;
  title: string;
  badge: string;
  description: string;
  body: string;
  parameters: string[];
  labels: string[];
  examples: string[];
  /** When true, send via castme_plain_utility_v1. */
  instant?: boolean;
};

export const STARTER_UTILITY_TEMPLATES: readonly StarterUtilityTemplate[] = [
  // —— Featured Template-N (match Page Instant trial / library cards) ——
  {
    id: 'template_28',
    name: 'membership_status_update',
    title: 'Template-28',
    badge: 'EN',
    description: 'Membership status update',
    body: "👑 Hello {{1}},\n\nHere's your latest membership information.\n\n🏆 {{2}}\n📅 {{3}}\n🟢 {{4}}\n\nReply YES to {{5}}.",
    parameters: ['customer_name', 'plan', 'date', 'status', 'cta'],
    labels: ['Customer name', 'Plan', 'Date', 'Status', 'CTA'],
    examples: ['John', 'Pro Membership', 'March 15, 2026', 'Active', 'manage your membership'],
  },
  {
    id: 'lib_28',
    name: 'pi_lib_28',
    title: 'Template-27',
    badge: 'EN',
    description: 'Account update with highlights + CTA',
    body: "Hi {{1}}, ❤❤\n\n💎 there's an update on your account: \n\n🏆 {{2}}\n🔔 {{3}}\n💸 {{4}}\n💵 {{5}}\n✅ {{6}}\n\nReply yes if you Want {{7}}📩",
    parameters: [
      'customer_name',
      'highlight_1',
      'highlight_2',
      'highlight_3',
      'highlight_4',
      'highlight_5',
      'cta_offer',
    ],
    labels: [
      'Customer name',
      'Highlight 1',
      'Highlight 2',
      'Highlight 3',
      'Highlight 4',
      'Highlight 5',
      'CTA offer',
    ],
    examples: [
      'Ahmed',
      'Bonus unlocked',
      'New reward',
      'Cashback added',
      'Wallet updated',
      'VIP access',
      'your free spins',
    ],
  },
  {
    id: 'lib_27',
    name: 'pi_lib_27',
    title: 'Template-26',
    badge: 'EN',
    description: 'Activation announcement with three rewards',
    body: 'Hey {{1}} 🔥, \n\n{{2}} just got ACTIVATED. 🎉\n\nNow Get : \n\n🎯 {{3}}\n🎯 {{4}}\n🎯 {{5}}\n\nReply if you need any assistance.',
    parameters: ['customer_name', 'what_is_activated', 'reward_1', 'reward_2', 'reward_3'],
    labels: ['Customer name', 'What is activated', 'Reward 1', 'Reward 2', 'Reward 3'],
    examples: ['Ahmed', 'VIP plan', 'Daily bonus', 'Fast support', 'Free spins'],
  },
  {
    id: 'lib_19',
    name: 'pi_lib_19',
    title: 'Template-19',
    badge: 'EN',
    description: 'Confirmation with four points + CTA',
    body: '{{1}} is confirmed 🔥🔥\n\n🎯 {{2}}\n🎯 {{3}}\n🎯 {{4}}\n🎯 {{5}}\n\n📩 Say yes if you want {{6}}',
    parameters: [
      'what_is_confirmed',
      'point_1',
      'point_2',
      'point_3',
      'point_4',
      'cta_offer',
    ],
    labels: ['What is confirmed', 'Point 1', 'Point 2', 'Point 3', 'Point 4', 'CTA offer'],
    examples: [
      'Your order',
      'Fast delivery',
      'Free returns',
      'Gift included',
      '24/7 support',
      'to confirm now',
    ],
  },
  {
    id: 'template_33',
    name: 'status_update_4_lines',
    title: 'Template-33',
    badge: 'EN',
    description: 'Four-line status checklist',
    body: '🔔 {{1}}\n\n✅ {{2}}\n\n✅ {{3}}\n\n✅ {{4}}\n\nReply if you need assistance.',
    parameters: ['headline', 'point_1', 'point_2', 'point_3'],
    labels: ['Headline', 'Point 1', 'Point 2', 'Point 3'],
    examples: ['Account Update', 'Balance added', 'Bonus active', 'Support ready'],
  },
  {
    id: 'lib_26',
    name: 'pi_lib_26',
    title: 'Template-25',
    badge: 'EN',
    description: 'Short activation confirmation',
    body: 'Hello {{1}} 🎁, {{2}} has been ACTIVATED for you! ❤',
    parameters: ['customer_name', 'what_is_activated'],
    labels: ['Customer name', 'What is activated'],
    examples: ['Ahmed', 'Your bonus'],
  },
  {
    id: 'lib_25',
    name: 'pi_lib_25',
    title: 'Template-24',
    badge: 'EN',
    description: 'Player status update with three points',
    body: 'Hello {{1}} 👋\n\nYour player status has been updated.\n\n✅ {{2}}\n🎁  {{3}}\n⚡  {{4}}\n\nReply if you need any assistance.',
    parameters: ['customer_name', 'update_1', 'update_2', 'update_3'],
    labels: ['Customer name', 'Update 1', 'Update 2', 'Update 3'],
    examples: ['Ahmed', 'Status upgraded', 'Bonus added', 'Faster payouts'],
  },
  {
    id: 'lib_24',
    name: 'pi_lib_24',
    title: 'Template-23',
    badge: 'EN',
    description: 'One-line active confirmation',
    body: 'Hello {{1}} ❤❤,\n\n{{2}} is now ACTIVE. 💸',
    parameters: ['customer_name', 'what_is_active'],
    labels: ['Customer name', 'What is active'],
    examples: ['Ahmed', 'Your account'],
  },
  {
    id: 'lib_22',
    name: 'pi_lib_22',
    title: 'Template-22',
    badge: 'EN',
    description: 'Confirmation with three details',
    body: 'Hi {{1}},🔥🔥\n\nYour {{2}} is now confirmed. ✅\n\n✅ {{3}}\n✅ {{4}}\n✅ {{5}}\n\nReply to this message if you have any questions.',
    parameters: ['customer_name', 'what_is_confirmed', 'detail_1', 'detail_2', 'detail_3'],
    labels: ['Customer name', 'What is confirmed', 'Detail 1', 'Detail 2', 'Detail 3'],
    examples: ['Ahmed', 'order', 'Fast delivery', 'Free returns', '24/7 support'],
  },
  {
    id: 'lib_21',
    name: 'pi_lib_21',
    title: 'Template-21',
    badge: 'EN',
    description: 'Update with current status list',
    body: 'Hey {{1}} 📢\n\nYour {{2}} has been successfully updated. ✅\n\n📌 Current Status:\n✅ {{3}}\n✅ {{4}}\n✅ {{5}}\n\nReply if you need any assistance.',
    parameters: ['customer_name', 'what_updated', 'status_1', 'status_2', 'status_3'],
    labels: ['Customer name', 'What updated', 'Status 1', 'Status 2', 'Status 3'],
    examples: ['Ahmed', 'account', 'Verified', 'Active', 'Ready'],
  },
  {
    id: 'lib_20',
    name: 'pi_lib_20',
    title: 'Template-20',
    badge: 'EN',
    description: 'Headline with three checklist points',
    body: '🔔 {{1}}\n\n✅ {{2}}\n\n✅ {{3}}\n\n✅ {{4}}\n\nReply if you need assistance.',
    parameters: ['headline', 'point_1', 'point_2', 'point_3'],
    labels: ['Headline', 'Point 1', 'Point 2', 'Point 3'],
    examples: ['Account Update', 'Balance added', 'Bonus active', 'Support ready'],
  },
  {
    id: 'lib_18',
    name: 'pi_lib_18',
    title: 'Template-18',
    badge: 'EN',
    description: 'Gift confirmed with CTA',
    body: '🔥 {{1}} \n\n🎁 {{2}} is confirmed 🎁\n\n✅ {{3}}\n✅ {{4}}\n\n📩 Say yes if you want {{5}}',
    parameters: ['customer_name', 'what_is_confirmed', 'benefit_1', 'benefit_2', 'cta_offer'],
    labels: ['Customer name', 'What is confirmed', 'Benefit 1', 'Benefit 2', 'CTA offer'],
    examples: ['Ahmed', 'Your gift', 'Bonus unlocked', 'Free delivery', 'your reward'],
  },
  {
    id: 'lib_17',
    name: 'pi_lib_17',
    title: 'Template-17',
    badge: 'EN',
    description: 'Account update completed note',
    body: '🔔 Hi {{1}}, your account update has been completed successfully. \n⌛ {{2}}',
    parameters: ['customer_name', 'status_note'],
    labels: ['Customer name', 'Status note'],
    examples: ['Ahmed', 'Ready in 2 minutes'],
  },
  {
    id: 'lib_13',
    name: 'pi_lib_13',
    title: 'Template-13',
    badge: 'EN',
    description: 'Ready notice with extra note',
    body: 'Hi {{1}} 👀,\n\nYour  {{2}} is ready.✅\n{{3}}\n\nReply if you have any questions.',
    parameters: ['customer_name', 'what_is_ready', 'extra_note'],
    labels: ['Customer name', 'What is ready', 'Extra note'],
    examples: ['Ahmed', 'order', 'You will get it in 2 days'],
  },
  {
    id: 'lib_12',
    name: 'pi_lib_12',
    title: 'Template-12',
    badge: 'EN',
    description: 'Headline with three status points',
    body: '📂 {{1}}\n\n🟢 {{2}}\n🟢 {{3}}\n🟢 {{4}}\n\nReply if you need assistance.',
    parameters: ['headline', 'point_1', 'point_2', 'point_3'],
    labels: ['Headline', 'Point 1', 'Point 2', 'Point 3'],
    examples: ['Account Summary', 'Profile verified', 'Wallet active', 'Support ready'],
  },
  {
    id: 'lib_10',
    name: 'pi_lib_10',
    title: 'Template-10',
    badge: 'EN',
    description: 'Confirmation checklist with time',
    body: 'Hi! {{1}} is now confirmed.\n\n✅ - {{2}}\n✅ - {{3}}\n✅ - {{4}}\n\nTime : {{5}} ⌛',
    parameters: ['what_is_confirmed', 'point_1', 'point_2', 'point_3', 'time'],
    labels: ['What is confirmed', 'Point 1', 'Point 2', 'Point 3', 'Time'],
    examples: ['Your order', 'Item packed', 'Payment received', 'On the way', '2 days'],
  },
  {
    id: 'lib_8',
    name: 'pi_lib_8',
    title: 'Template-8',
    badge: 'EN',
    description: 'Payment confirmed with CTA',
    body: '🔥 {{1}} \n\n💸 {{2}} is confirmed 💸\n\n📩 Say yes if you want {{3}}',
    parameters: ['customer_name', 'what_is_confirmed', 'cta_offer'],
    labels: ['Customer name', 'What is confirmed', 'CTA offer'],
    examples: ['Ahmed', 'Your payment', 'fast delivery'],
  },
  {
    id: 'lib_5',
    name: 'pi_lib_5',
    title: 'Template-5',
    badge: 'EN',
    description: 'Account info updated',
    body: '🔔 {{1}}\n\nYour account information has been updated.\n\n📄 {{2}}\n📅 {{3}}\n🔖 {{4}}\n\nReply if you need assistance.',
    parameters: ['customer_name', 'detail_1', 'detail_2', 'detail_3'],
    labels: ['Customer name', 'Detail 1', 'Detail 2', 'Detail 3'],
    examples: ['Ahmed', 'New balance', 'Updated today', 'Reference #24'],
  },
  {
    id: 'lib_4',
    name: 'pi_lib_4',
    title: 'Template-4',
    badge: 'EN',
    description: 'Information refreshed',
    body: '{{1}} ❤\n\nYour information has been refreshed.\n\n✅ {{2}}\n📂 {{3}}\n🔖 {{4}}\n\nReply if you need assistance.',
    parameters: ['customer_name', 'detail_1', 'detail_2', 'detail_3'],
    labels: ['Customer name', 'Detail 1', 'Detail 2', 'Detail 3'],
    examples: ['Ahmed', 'Verified', 'New report', 'Reference #24'],
  },
  {
    id: 'lib_3',
    name: 'pi_lib_3',
    title: 'Template-3',
    badge: 'EN',
    description: 'Status updated details',
    body: '{{1}}\n\nYour Status has been Updated\n\n✔️ {{2}}\n📄 {{3}}\n🕒 {{4}}\n\nReply if you need assistance.',
    parameters: ['customer_name', 'detail_1', 'detail_2', 'detail_3'],
    labels: ['Customer name', 'Detail 1', 'Detail 2', 'Detail 3'],
    examples: ['Ahmed', 'Verified account', 'New report', 'Updated 5 min ago'],
  },
  {
    id: 'premium_1',
    name: 'pi_order_status_premimum',
    title: 'Template-32',
    badge: 'EN',
    description: 'Plan activated checklist',
    body: 'Hi {{1}} 👏\n\nYour {{2}} is activate right now... \n\n✅ {{3}}\n\n✅ {{4}}\n\n✅ {{5}}\n\n✅ {{6}}\n\nReply if you have any questions.',
    parameters: ['customer_name', 'plan_offer', 'benefit_1', 'benefit_2', 'benefit_3', 'benefit_4'],
    labels: ['Customer name', 'Plan / offer', 'Benefit 1', 'Benefit 2', 'Benefit 3', 'Benefit 4'],
    examples: ['Ahmed', 'VIP plan', 'Daily updates', 'Fast support', 'Bonus rewards', 'Easy renew'],
  },
  {
    id: 'starter_1',
    name: 'pi_account_status_active',
    title: 'Template-31',
    badge: 'EN',
    description: 'Account now active',
    body: 'Hello  {{1}}👀,\n\nYour {{2}} is now ACTIVE. ✅\n\n💸 {{3}}\n🏆 {{4}}\n\nReply if you have any questions. ❤',
    parameters: ['customer_name', 'what_is_active', 'perk_1', 'perk_2'],
    labels: ['Customer name', 'What is active', 'Perk 1', 'Perk 2'],
    examples: ['Ahmed', 'account', 'Welcome bonus unlocked', 'Priority support on'],
  },
  {
    id: 'basic_6',
    name: 'pi_support_ticket',
    title: 'Template-30',
    badge: 'EN',
    description: 'Ticket resolved',
    body: 'Hi {{1}}, 🔥🔥\n\nYour ✅ {{2}} is resolved. ✅\n\n👀 {{3}} 👀\n\nReply if you have any questions. ❤',
    parameters: ['customer_name', 'ticket_issue', 'resolution_note'],
    labels: ['Customer name', 'Ticket / issue', 'Resolution note'],
    examples: ['Jane', 'ticket #543', 'Your account will not get issue now.'],
  },
  {
    id: 'basic_5',
    name: 'pi_delivery_confirmation',
    title: 'Template-29',
    badge: 'EN',
    description: 'Delivery arrived',
    body: '🔥 Hey {{1}}, 🔥\n\n✅✅ Your {{2}} has arrived. ✅✅\n\n{{3}} 🎁\n\nReply if you have any questions.',
    parameters: ['customer_name', 'what_arrived', 'extra_note'],
    labels: ['Customer name', 'What arrived', 'Extra note'],
    examples: ['Jane', 'parcel', 'You will get it in 2 days.'],
  },
  {
    id: 'basic_4',
    name: 'pi_account_update',
    title: 'Template-16',
    badge: 'EN',
    description: 'Balance confirmed',
    body: 'Hello {{1}},❤\n\nYour {{2}} confirmed.✅✅\n\n{{3}}\n\nReply if you have any questions.❤',
    parameters: ['customer_name', 'what_confirmed', 'detail_line'],
    labels: ['Customer name', 'What confirmed', 'Detail line'],
    examples: ['John', 'account balance is', 'You have $41 in your wallet now.'],
  },
  {
    id: 'basic_3',
    name: 'pi_account_notification',
    title: 'Template-15',
    badge: 'EN',
    description: 'Wallet updated',
    body: 'Hello {{1}}, ❤❤\n\n✅ {{2}} has been updated✅\n\n{{3}} ⏳\n\nReply if you have any questions. ❤',
    parameters: ['customer_name', 'what_updated', 'status_note'],
    labels: ['Customer name', 'What updated', 'Status note'],
    examples: ['John', 'Your wallet', 'You have now $34 remaining.'],
  },
  {
    id: 'basic_2',
    name: 'pi_invoice_status',
    title: 'Template-14',
    badge: 'EN',
    description: 'Payment complete',
    body: 'Hi {{1}} ,👀\n\n💸Your {{2}} is complete.✅✅\n\n{{3}}  🎉\nReply if you have any questions.',
    parameters: ['customer_name', 'what_completed', 'follow_up_question'],
    labels: ['Customer name', 'What completed', 'Follow-up question'],
    examples: ['John', 'Invoice ID 24', 'Have you received the packet?'],
  },
  {
    id: 'basic_1',
    name: 'pi_order_confirmation',
    title: 'Template-11',
    badge: 'EN',
    description: 'Order ready + CTA',
    body: 'Hi {{1}},  #{{2}} is ready🔥🔥\n\n📩 Say yes if you want {{3}}',
    parameters: ['customer_name', 'order_code', 'cta_offer'],
    labels: ['Customer name', 'Order / code', 'CTA offer'],
    examples: ['John', '543', 'to get it delivered in 2 days'],
  },
  {
    id: 'simple_1',
    name: 'pi_order_confirm_2',
    title: 'Template-9',
    badge: 'EN',
    description: 'Quick confirmation',
    body: '🔥 Hi your {{1}}, is Now confirmed✅',
    parameters: ['what_is_confirmed'],
    labels: ['What is confirmed'],
    examples: ['order #120'],
  },
  {
    id: 'premium_2',
    name: 'pi_daily_summary_update',
    title: 'Template-7',
    badge: 'EN',
    description: 'Daily summary report',
    body: 'Hi {{1}}, \n\nHere is your daily {{2}} summary: \n\n✅ {{3}}\n✅ {{4}}\n✅ {{5}}\n\nLet us know if you need help! 💬',
    parameters: ['customer_name', 'summary_topic', 'highlight_1', 'highlight_2', 'highlight_3'],
    labels: ['Customer name', 'Summary topic', 'Highlight 1', 'Highlight 2', 'Highlight 3'],
    examples: ['Ahmed', 'earnings', 'Sales up 12%', '3 new leads', '1 refund pending'],
  },

  // —— Instant: shared castme_plain_utility_v1 ——
  {
    id: 'instant_bonus_active',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Bonus Active',
    badge: 'Instant',
    description: 'Shared plain UTILITY — no new Meta template once plain is ready',
    body: 'Hello {{1}} ❤️❤️, {{2}} is now ACTIVE. ☘️',
    parameters: ['customer_name', 'what_is_active'],
    labels: ['Customer name', 'What is active'],
    examples: ['Friend', '30% Bonus'],
    instant: true,
  },
  {
    id: 'instant_vip_unlock',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · VIP Unlocked',
    badge: 'Instant',
    description: 'Instant plain UTILITY',
    body: 'Hey {{1}} 🔥, your {{2}} is unlocked. Reply YES for help. ✅',
    parameters: ['customer_name', 'vip_perk'],
    labels: ['Customer name', 'VIP / perk'],
    examples: ['Friend', 'VIP access'],
    instant: true,
  },
  {
    id: 'instant_wallet_update',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Wallet Updated',
    badge: 'Instant',
    description: 'Instant account update',
    body: 'Hi {{1}} 👀, your {{2}} was updated. {{3}} 💸',
    parameters: ['customer_name', 'what_updated', 'detail'],
    labels: ['Customer name', 'What updated', 'Detail'],
    examples: ['Friend', 'wallet', 'Balance is ready to use.'],
    instant: true,
  },
  {
    id: 'instant_offer_cta',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Offer CTA',
    badge: 'Instant',
    description: 'Short offer with reply CTA',
    body: "Hello {{1}} 🎁, {{2}} is ready for you. Reply YES if you want {{3}}.",
    parameters: ['customer_name', 'offer_name', 'cta'],
    labels: ['Customer name', 'Offer', 'CTA'],
    examples: ['Friend', "today's bonus", 'free spins'],
    instant: true,
  },
  {
    id: 'instant_status_ok',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Status Confirmed',
    badge: 'Instant',
    description: 'One-line confirmation',
    body: 'Hi {{1}} ✅, your {{2}} is confirmed. Reply if you need help.',
    parameters: ['customer_name', 'what_confirmed'],
    labels: ['Customer name', 'What confirmed'],
    examples: ['Friend', 'account status'],
    instant: true,
  },
  {
    id: 'instant_reward_ready',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Reward Ready',
    badge: 'Instant',
    description: 'Reward notice',
    body: '{{1}}, your {{2}} is ready 🎉. {{3}}',
    parameters: ['customer_name', 'reward', 'extra'],
    labels: ['Customer name', 'Reward', 'Extra note'],
    examples: ['Friend', 'daily reward', 'Claim it in the app.'],
    instant: true,
  },
  {
    id: 'instant_support_done',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Issue Resolved',
    badge: 'Instant',
    description: 'Support resolved',
    body: 'Hi {{1}}, your {{2}} is resolved ✅. {{3}}',
    parameters: ['customer_name', 'issue', 'note'],
    labels: ['Customer name', 'Issue', 'Note'],
    examples: ['Friend', 'request', 'Thanks for your patience.'],
    instant: true,
  },
  {
    id: 'instant_reminder',
    name: INSTANT_PLAIN_UTILITY_NAME,
    title: 'Instant · Reminder',
    badge: 'Instant',
    description: 'Soft reminder',
    body: 'Hello {{1}} 🔔, reminder: {{2}}. Reply if you need assistance.',
    parameters: ['customer_name', 'reminder'],
    labels: ['Customer name', 'Reminder'],
    examples: ['Friend', 'your bonus expires soon'],
    instant: true,
  },
] as const;

export const STARTER_UTILITY_TEMPLATE_COUNT = STARTER_UTILITY_TEMPLATES.length;
